### ISSUE TITLE
Can we bump the semver on typedoc dependency?

### ISSUE THREAD

**Issue by richardspence** [christopherthielen/typedoc-plugin-internal-external#225]
In the package json, this package currently requires a peer dependency on typedoc =  `^0.8.0`, but typedoc is currently published at `0.14.0`.  Can we update to `^0.14.0` or maybe `^0`?

**Comment by richardspence** [comment]
The dev dependency was already set to   `"typedoc": "^0.14.2", ` so it was a little odd for the published package to have a lower version.  Sounds like a bug?

**Comment by richardspence** [comment]
Ping @christopherthielen

**Comment by christopherthielen** [comment]
thanks for reporting!  fixed in 7df47addd5c2559f1539a3528f3dea547082b27f
